### ISSUE TITLE
[BUG] Close Combat Archer crashes Game

### ISSUE THREAD

**Issue by Alsi102** [Battle-Brothers-Legends/Legends-public#5]
* **Versions**
 Game: [e.g. 1.5.0.15]
 Legends [e.g. 19.0.0]

* **Describe the bug**
The new Perk "Close Combat Archer" doesnt work properly. A guy who had it already threw Javelins at Bandits but nothing happened other than losing AP. There were no animation of throwing something and it never hit anything (as if nothing has ever been thrown). After testing it with another Bro (leveled it specifically for testing) on a Wiederganger, it crashed the game.

* **Your log**
Please post your log so we can help. 
Your log is found in: ```C:\Users\YourName\Documents\Battle Brothers\log.html```
The log is constantly updated during game and is reset each time you open the game and it is best to upload the log when the error first occurred. Make sure you just zip the log file as it is. We will not bother opening files that don't end with `.html`.

[log.zip](https://github.com/user-attachments/files/18223097/log.zip)

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**

* **To Reproduce**

* **Screenshots**

* **Additional context**

* **Additional Note**
We will not provide support for older legends versions. If you are able to, come to our discord, so we can provide more hands on support.

**Comment by BreakyZ** [comment]
We've already got a fix for this - will be fixed when 19.0.2 drops
